### ISSUE TITLE
Difference between FFVideoEncoder and AVSegmentingAppleEncoder?

### ISSUE THREAD

**Issue by justinmakaila** [chrisballinger/FFmpeg-iOS-Encoder#3]
I'm trying to build a live streaming app and I've used your library as a model. I understand that `FFVideoEncoder` uses `FFMPEG` to encode H.264 video with AAC audio, but doesn't the `AVSegmentingAppleEncoder` do the same? It doesn't appear that any of the `AppleEncoders` use any `FF...Encoder` libs; do they still do the same thing? Or do they only put out .mp4, while the `FFEncoders` CAN be used to convert to H.264 video for streaming?

**Comment by chrisballinger** [comment]
The ffmpeg encoder sucks because it uses software and is slow. The apple
encoder is hardware accelerated so its much faster and better quality.
However it doesn't support streaming so you have to start and stop the
encoder and send it in chunks instead, unless you figure out how to extract
the NAL units in real time while the file is being written

On Mar 30, 2013, at 9:30 AM, justinmakaila notifications@github.com wrote:

I'm trying to build a live streaming app and I've used your library as a
model. I understand that FFVideoEncoder uses FFMPEG to encode H.264 video
with AAC audio, but doesn't the AVSegmentingAppleEncoder do the same? It
doesn't appear that any of the AppleEncoders use any FF...Encoder libs; do
they still do the same thing? Or do they only put out .mp4, while the
FFEncoders CAN be used to convert to H.264 video for streaming?

—
Reply to this email directly or view it on
GitHubhttps://github.com/chrisballinger/FFmpeg-iOS-Encoder/issues/3
.

**Comment by m1entus** [comment]
Did you solve how to live stream mp4 chunks which are created by FFmpeg-iOS-Encoder ?

**Comment by justinmakaila** [comment]
yes, i used afnetworking to "stream" the files over HTTP to a python server for serialization of M3U8 files for playback. the difficult part is ensuring that transcoding can happen fast enough to actually scale

I also have a library that's _almost_ functional in reading raw nal units from the files as it's being written and streams them over RTMP
